import 'package:flutter/material.dart';

class AppStrings {
  static String currentLanguage = 'english';

  static Locale getLocale(String key) {
    switch (key) {
      case 'hindi': return const Locale('hi');
      case 'haryanvi': return const Locale('hi', 'IN');
      case 'punjabi': return const Locale('pa');
      case 'sanskrit': return const Locale('sa');
      case 'tamil': return const Locale('ta');
      case 'telugu': return const Locale('te');
      case 'kannada': return const Locale('kn');
      case 'malayalam': return const Locale('ml');
      case 'odia': return const Locale('or');
      case 'bengali': return const Locale('bn');
      case 'marathi': return const Locale('mr');
      case 'gujarati': return const Locale('gu');
      case 'russian': return const Locale('ru');
      default: return const Locale('en');
    }
  }

  static const Map<String, Map<String, String>> _strings = {
    'english': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'Online',
      'chat': 'Chat',
      'alerts': 'Alerts',
      'profile': 'Profile',
      'welcome_back': 'Welcome Back! 👋',
      'aura_waiting': 'AURA is waiting for you...',
      'email': 'Email address',
      'password': 'Password',
      'login': 'Login ✦',
      'or': 'or',
      'google_login': 'Continue with Google',
      'create_account': 'Create Account! ✨',
      'username_taken': 'Username has been taken by another user.',
      'new_here': 'New here? ',
      'forgot_password': 'Forgot password?',
      'smart_alarms': 'Smart Alarms ⏰',
      'aura_talk': 'Talk to AURA...',
      'upgrade': 'Upgrade',
      'voice_unlock': 'Unlock Voice AI — ₹399/month',
      'settings': 'SETTINGS',
      'free_plan': 'FREE Plan',
      'upgrade_unlock': 'Upgrade to unlock everything',
      'beyond_intelligence': 'Beyond Intelligence',
      'initializing': 'Initializing AURA...',
      'verify_email': 'Verify Your Email',
      'email_sent_to': 'A verification link has been sent to:',
      'click_to_verify': 'Please verify your email and then click "I Have Verified".',
      'i_have_verified': 'I Have Verified ✓',
      'resend_email': 'Resend Email',
      'timer_expired': 'Verification expired. Please sign up again.',
      'account_created_success': 'Account Successfully Created',
      'please_login_continue': 'Please Login To Continue',
      'full_name': 'Full Name',
      'name_email_pass_req': 'Name, Email and Password are required.',
      'username_req': 'Please enter a unique username.',
      'bio_hint': 'Bio - Tell us something about yourself',
      'choose_avatar': 'CHOOSE AVATAR',
      'aura_personality': 'AURA PERSONALITY',
      'friendly_desc': 'Warm and caring',
      'savage_desc': 'Will roast you',
      'motivator_desc': 'Always boosts you',
      'chill_desc': 'Relax mode always',
      'next': 'Next →',
      'enter_email': 'Please enter your email',
      'invalid_email': 'Invalid email format',
      'enter_password': 'Please enter your password',
      'password_too_short': 'Password must be at least 6 characters',
      'email_not_verified': 'Email is not verified. A verification link has been sent.',
      'login_failed': 'Login failed. Please try again.',
      'google_cancel': 'Google login was cancelled.',
      'google_timeout': 'Google login timed out.',
      'google_setup_error': 'Google login setup is incomplete.',
      'future_waiting': 'Your future is waiting inside...',
      'welcome_sine': 'Welcome to Sine AI',
      'enter_email_reset': 'Please enter your email to reset password',
      'reset_link_sent': 'Password reset link sent to your email',
      'error_reset_link': 'Error sending reset link.',
      'account_not_found': 'Account not found',
      'incorrect_password': 'Incorrect password',
      'error_generic': 'Error. Please try again.',
      'friendly': 'Friendly 😊',
      'savage': 'Savage 😈',
      'motivator': 'Motivator 💪',
      'chill': 'Chill 😎',
      'privacy_title': 'Privacy',
      'privacy_desc': 'Your account is secure with Firebase Auth. Profile data is saved in Firestore.',
      'done': 'Done',
      'default_user_name': 'SINE AI User',
      'default_bio': 'Building something amazing ✨',
      'chats': 'Chats',
      'goals': 'Goals',
      'streak': 'Streak',
      'language_label': 'Language',
      'appearance': 'Appearance',
      'themes_free': 'Themes are free',
      'notifications': 'Notifications',
      'notifications_desc': 'SINE Alert settings',
      'aura_customization': 'Customize your AI',
      'privacy_label': 'Privacy',
      'privacy_sub': 'Data & security',
      'subscription_label': 'Subscription',
      'subscription_sub': 'Plans & billing',
      'logout_label': 'Logout',
      'logout_sub': 'Sign out of account',
      'choose_language': 'Choose Language',
      'pro_title': 'SINE AI Pro',
      'pro_message': 'Unlock unlimited chat, AURA voice, and premium features.',
      'chat_initial': 'Namaste! I am SINE AI. How can I help you today?',
      'chat_hint': 'Message SINE AI...',
      'error_internet': 'Please check your internet connection! 🔌',
      'error_generic_short': 'Oops! Something went wrong. 😅',
      'payment_coming_soon': 'Payment screen will be connected in the next step.',
      'unlock_button': 'Unlock',
      'plan_dekho': 'View Plan',
      'abhi_nahi': 'Not now',
      'coupon_hint': 'Coupon code',
      'coupon_success': 'Coupon applied successfully!',
      'coupon_invalid': 'Invalid coupon code.',
      'coupon_login_req': 'Please login first to use coupon.',
      'coupon_full': 'This coupon has reached its limit.',
      'pro_unlock_success': 'Founder Pro unlocked!',
    },
    'hindi': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ऑनलाइन',
      'chat': 'चैट',
      'alerts': 'अलर्ट',
      'profile': 'प्रोफाइल',
      'welcome_back': 'वापस आए! 👋',
      'aura_waiting': 'AURA आपका इंतजार कर रहा था...',
      'email': 'ईमेल पता',
      'password': 'पासवर्ड',
      'login': 'लॉगिन करें ✦',
      'or': 'या',
      'google_login': 'Google से जारी रखें',
      'create_account': 'अकाउंट बनाएं! ✨',
      'username_taken': 'यह username किसी और user ने ले लिया है.',
      'new_here': 'नए हैं? ',
      'forgot_password': 'पासवर्ड भूल गए?',
      'smart_alarms': 'स्मार्ट अलार्म ⏰',
      'aura_talk': 'AURA से बात करें...',
      'upgrade': 'अपग्रेड',
      'voice_unlock': 'Voice AI अनलॉक करें — ₹399/माह',
      'settings': 'सेटिंग्स',
      'free_plan': 'फ्री प्लान',
      'upgrade_unlock': 'सब कुछ अनलॉक करें',
      'beyond_intelligence': 'बुद्धि से परे',
      'initializing': 'AURA शुरू हो रहा है...',
      'verify_email': 'ईमेल वेरीफाई करें',
      'email_sent_to': 'हमने वेरिफिकेशन लिंक यहाँ भेजा है:',
      'click_to_verify': 'ईमेल वेरीफाई करके "Maine Verify Kar Liya" पर क्लिक करें.',
      'i_have_verified': 'मैंने वेरीफाई कर लिया ✓',
      'resend_email': 'ईमेल दोबारा भेजें',
      'timer_expired': 'समय खत्म हो गया. कृपया दोबारा अकाउंट बनाएं.',
      'account_created_success': 'अकाउंट सफलतापूर्वक बन गया',
      'please_login_continue': 'आगे बढ़ने के लिए लॉगिन करें',
      'full_name': 'पूरा नाम',
      'name_email_pass_req': 'नाम, ईमेल और पासवर्ड जरूरी हैं.',
      'username_req': 'कृपया एक यूनिक यूजरनेम डालें.',
      'bio_hint': 'बायो - अपने बारे में कुछ लिखें',
      'choose_avatar': 'अवतार चुनें',
      'aura_personality': 'AURA की पर्सनालिटी',
      'friendly_desc': 'दयालु और मददगार',
      'savage_desc': 'रोस्ट करेगा आपको',
      'motivator_desc': 'हमेशा मोटिवेट करेगा',
      'chill_desc': 'हमेशा रिलैक्स मोड',
      'next': 'आगे बढ़ें →',
      'enter_email': 'कृपया अपना ईमेल डालें',
      'invalid_email': 'ईमेल का फॉर्मेट सही नहीं है',
      'enter_password': 'कृपया अपना पासवर्ड डालें',
      'password_too_short': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      'email_not_verified': 'ईमेल वेरीफाई नहीं है. वेरिफिकेशन लिंक भेज दिया गया है.',
      'login_failed': 'लॉगिन नहीं हो पाया. कृपया दोबारा कोशिश करें.',
      'google_cancel': 'Google लॉगिन रद्द कर दिया गया.',
      'google_timeout': 'Google लॉगिन का समय समाप्त हो गया.',
      'google_setup_error': 'Google लॉगिन सेटअप पूरा नहीं है.',
      'future_waiting': 'आपका भविष्य अंदर इंतज़ार कर रहा है...',
      'welcome_sine': 'Sine AI में आपका स्वागत है',
      'enter_email_reset': 'पासवर्ड रीसेट करने के लिए ईमेल डालें',
      'reset_link_sent': 'पासवर्ड रीसेट लिंक आपके ईमेल पर भेज दिया गया है',
      'error_reset_link': 'लिंक भेजने में त्रुटि हुई।',
      'account_not_found': 'अकाउंट नहीं मिला।',
      'incorrect_password': 'गलत पासवर्ड।',
      'error_generic': 'त्रुटि हुई। फिर कोशिश करें।',
      'friendly': 'मिलनसार 😊',
      'savage': 'सैवेज 😈',
      'motivator': 'प्रेरक 💪',
      'chill': 'शांत 😎',
      'privacy_title': 'प्राइवेसी',
      'privacy_desc': 'आपका अकाउंट Firebase Auth के साथ सुरक्षित है।',
      'done': 'हो गया',
      'default_user_name': 'SINE AI यूजर',
      'default_bio': 'कुछ अद्भुत बना रहे हैं ✨',
      'chats': 'चैट',
      'goals': 'लक्ष्य',
      'streak': 'लगातार',
      'language_label': 'भाषा',
      'appearance': 'दिखावट',
      'themes_free': 'थीम्स फ्री हैं',
      'notifications': 'नोटिफिकेशन',
      'notifications_desc': 'SINE अलर्ट सेटिंग्स',
      'aura_customization': 'अपनी AI को कस्टमाइज़ करें',
      'privacy_label': 'प्राइवेसी',
      'privacy_sub': 'डेटा और सुरक्षा',
      'subscription_label': 'सब्सक्रिप्शन',
      'subscription_sub': 'प्लान और बिलिंग',
      'logout_label': 'लॉगआउट',
      'logout_sub': 'अकाउंट से बाहर निकलें',
      'choose_language': 'भाषा चुनें',
      'pro_title': 'SINE AI प्रो',
      'pro_message': 'अनलिमिटेड चैट, AURA वॉइस और प्रीमियम फीचर्स अनलॉक करें।',
      'chat_initial': 'नमस्ते! मैं SINE AI हूँ। आज मैं आपकी क्या मदद कर सकता हूँ?',
      'chat_hint': 'SINE AI को मैसेज लिखें...',
    },
    'haryanvi': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ऑनलाइन',
      'chat': 'बातचीत',
      'alerts': 'अलर्ट',
      'profile': 'प्रोफाइल',
      'welcome_back': 'आ गया भाई! 👋',
      'aura_waiting': 'AURA तेरी बाट देख्या करे था...',
      'email': 'ईमेल पता',
      'password': 'पासवर्ड',
      'login': 'लॉगिन कर ✦',
      'or': 'या फेर',
      'google_login': 'Google गेल चाल',
      'create_account': 'नया खाता बना! ✨',
      'username_taken': 'यो नाम तो किसे और ने ले लिया भाई.',
      'new_here': 'नया है के? ',
      'forgot_password': 'पासवर्ड भूल गया के?',
      'smart_alarms': 'स्मार्ट अलार्म ⏰',
      'aura_talk': 'AURA ते बात कर...',
      'upgrade': 'अपग्रेड',
      'voice_unlock': 'आवाज आली AI खोल — ₹399/महिना',
      'settings': 'सेटिंग',
      'free_plan': 'फ्री प्लान',
      'upgrade_unlock': 'सारा कीम खोल ले',
      'beyond_intelligence': 'अकल ते भी ऊपर',
      'initializing': 'AURA त्यार होवे है...',
      'verify_email': 'ईमेल देख ले एक बार',
      'email_sent_to': 'लिंक ओड़े भेज दिया है:',
      'click_to_verify': 'ईमेल चेक करके "Maine Verify Kar Liya" पे दाब दे.',
      'i_have_verified': 'कर लिया वेरीफाई ✓',
      'resend_email': 'दोबारा भेज',
      'timer_expired': 'टेम निकल गया. दोबारा बना ले खाता.',
      'account_created_success': 'खाता बन गया भाई',
      'please_login_continue': 'ईब लॉगिन कर ले',
      'full_name': 'पूरा नाम',
      'name_email_pass_req': 'नाम, ईमेल और पासवर्ड जरूरी हैं.',
      'username_req': 'एक बढ़िया सा नाम लिख.',
      'bio_hint': 'बायो - अपने बारे में कुछ बता',
      'choose_avatar': 'फोटो चुन ले',
      'aura_personality': 'AURA का सुभाव',
      'friendly_desc': 'बढ़िया और मददगार',
      'savage_desc': 'लठ गाड़ देगा',
      'motivator_desc': 'जोश भर देगा',
      'chill_desc': 'कती जमा शांति',
      'next': 'आगे चाल →',
      'enter_email': 'ईमेल डाल दे लाडले',
      'invalid_email': 'ईमेल सही कोन्या',
      'enter_password': 'पासवर्ड लिख दे',
      'password_too_short': 'पासवर्ड कम ते कम 6 अक्षर का होणा चाहिए',
      'email_not_verified': 'ईमेल वेरीफाई कोन्या. लिंक भेज दिया है.',
      'login_failed': 'लॉगिन कोन्या होया. दोबारा देख.',
      'google_cancel': 'Google लॉगिन काट दिया.',
      'google_timeout': 'टेम ज्यादा ले गया Google.',
      'google_setup_error': 'Google में कुछ दिक्कत है.',
      'future_waiting': 'तेरा भविष्य भीतर बाट देख्या करे...',
      'welcome_sine': 'Sine AI में तेरा स्वागत है',
      'enter_email_reset': 'पासवर्ड बदलण खातर ईमेल लिख',
      'reset_link_sent': 'पासवर्ड बदलण का लिंक भेज दिया है',
      'error_reset_link': 'लिंक भेजण में दिक्कत आगी भाई।',
      'account_not_found': 'अकाउंट कोन्या मिला।',
      'incorrect_password': 'पासवर्ड गलत है लाडले।',
      'error_generic': 'दिक्कत आगी भाई। दोबारा देख।',
      'friendly': 'बढ़िया सुभाव 😊',
      'savage': 'कसुता 😈',
      'motivator': 'जोश्याला 💪',
      'chill': 'जमा ठण्डा 😎',
      'privacy_title': 'प्राइवेसी',
      'privacy_desc': 'तेरा खाता Firebase गेल सुरक्षित है।',
      'done': 'हो गया',
      'default_user_name': 'SINE AI का मानस',
      'default_bio': 'कुछ कसुता बना रहे सां ✨',
      'chats': 'बातचीत',
      'goals': 'लक्ष्य',
      'streak': 'लगातार',
      'language_label': 'बोली',
      'appearance': 'दिखावट',
      'themes_free': 'थीम्स फ्री हैं भाई',
      'notifications': 'नोटिफिकेशन',
      'notifications_desc': 'SINE अलर्ट सेटिंग',
      'aura_customization': 'अपनी AI ने अपने हिसाब ते कर ले',
      'privacy_label': 'प्राइवेसी',
      'privacy_sub': 'डेटा और सुरक्षा',
      'subscription_label': 'सब्सक्रिप्शन',
      'subscription_sub': 'प्लान और पैसे',
      'logout_label': 'लॉगआउट',
      'logout_sub': 'खाते ते बाहर चाल',
      'choose_language': 'बोली चुन ले',
      'pro_title': 'SINE AI प्रो',
      'pro_message': 'अनलिमिटेड चैट और कसुते फीचर्स खोल ले।',
      'chat_initial': 'राम-राम! मैं हूँ SINE AI। बता भाई आज के सेवा करूँ?',
      'chat_hint': 'SINE AI ने मैसेज लिख...',
    },
    'punjabi': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ਆਨਲਾਈਨ',
      'chat': 'ਚੈਟ',
      'alerts': 'ਅਲਰਟ',
      'profile': 'ਪ੍ਰੋਫਾਈਲ',
      'welcome_back': 'ਵਾਪਸ ਆਏ! 👋',
      'aura_waiting': 'AURA ਤੁਹਾਡੀ ਉਡੀਕ ਕਰ ਰਿਹਾ ਸੀ...',
      'email': 'ਈਮੇਲ ਪਤਾ',
      'password': 'ਪਾਸਵਰਡ',
      'login': 'ਲੌਗਿਨ ਕਰੋ ✦',
      'or': 'ਜਾਂ',
      'google_login': 'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
      'create_account': 'ਖਾਤਾ ਬਣਾਓ! ✨',
      'username_taken': 'ਇਹ username ਕਿਸੇ ਹੋਰ user ਨੇ ਲੈ ਲਿਆ ਹੈ.',
      'new_here': 'ਨਵੇਂ ਹੋ? ',
      'forgot_password': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
      'smart_alarms': 'ਸਮਾਰਟ ਅਲਾਰਮ ⏰',
      'aura_talk': 'AURA ਨਾਲ ਗੱਲ ਕਰੋ...',
      'upgrade': 'ਅੱਪਗ੍ਰੇਡ',
      'voice_unlock': 'Voice AI ਅਨਲੌਕ ਕਰੋ — ₹399/ਮਹੀਨਾ',
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'free_plan': 'ਮੁਫਤ ਯੋਜਨਾ',
      'upgrade_unlock': 'ਸਭ ਕੁਝ ਅਨਲੌਕ ਕਰੋ',
      'beyond_intelligence': 'ਬੁੱਧੀ ਤੋਂ ਪਰੇ',
      'initializing': 'AURA ਸ਼ੁਰੂ ਹੋ ਰਿਹਾ ਹੈ...',
      'verify_email': 'ਈਮੇਲ ਵੈਰੀਫਾਈ ਕਰੋ',
      'email_sent_to': 'ਵੈਰੀਫਿਕੇਸ਼ਨ ਲਿੰਕ ਇੱਥੇ ਭੇਜਿਆ ਗਿਆ ਹੈ:',
      'click_to_verify': 'ਈਮੇਲ ਵੈਰੀਫਾਈ ਕਰਕੇ "Maine Verify Kar Liya" ਤੇ ਕਲਿੱਕ ਕਰੋ.',
      'i_have_verified': 'ਮੈਂ ਵੈਰੀਫਾਈ ਕਰ ਲਿਆ ✓',
      'resend_email': 'ਈਮੇਲ ਦੁਬਾਰਾ ਭੇਜੋ',
      'timer_expired': 'ਸਮਾਂ ਖਤਮ ਹੋ ਗਿਆ. ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਖਾਤਾ ਬਣਾਓ.',
      'account_created_success': 'ਖਾਤਾ ਸਫਲਤਾਪੂਰਵਕ ਬਣ ਗਿਆ',
      'please_login_continue': 'ਅੱਗੇ ਵਧਣ ਲਈ ਲੌਗਿਨ ਕਰੋ',
      'full_name': 'ਪੂਰਾ ਨਾਮ',
      'name_email_pass_req': 'ਨਾਮ, ਈਮੇਲ ਅਤੇ ਪਾਸਵਰਡ ਜ਼ਰੂਰੀ ਹਨ.',
      'username_req': 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਯੂਨੀਕ ਯੂਜ਼ਰਨੇਮ ਪਾਓ.',
      'bio_hint': 'ਬਾਇਓ - ਆਪਣੇ ਬਾਰੇ ਕੁਝ ਲਿਖੋ',
      'choose_avatar': 'ਅਵਤਾਰ ਚੁਣੋ',
      'aura_personality': 'AURA ਦੀ ਸ਼ਖਸੀਅਤ',
      'friendly_desc': 'ਦਿਆਲੂ ਅਤੇ ਮਦਦਗਾਰ',
      'savage_desc': 'ਰੋਸਟ ਕਰੇਗਾ ਤੁਹਾਨੂੰ',
      'motivator_desc': 'ਹਮੇਸ਼ਾ ਮੋਟੀਵੇਟ ਕਰੇਗਾ',
      'chill_desc': 'ਹਮੇਸ਼ਾ ਰਿਲੈਕਸ ਮੋਡ',
      'next': 'ਅੱਗੇ ਵਧੋ →',
      'enter_email': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਈਮੇਲ ਪਾਓ',
      'invalid_email': 'ਈਮੇਲ ਦਾ ਫਾਰਮੈਟ ਸਹੀ ਨਹੀਂ ਹੈ',
      'enter_password': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਪਾਸਵਰਡ ਪਾਓ',
      'password_too_short': 'ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ',
      'email_not_verified': 'ਈਮੇਲ ਵੈਰੀਫਾਈ ਨਹੀਂ ਹੈ. ਲਿੰਕ ਭੇਜ ਦਿੱਤਾ ਗਿਆ ਹੈ.',
      'login_failed': 'ਲੌਗਿਨ ਨਹੀਂ ਹੋ ਸਕਿਆ. ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ.',
      'google_cancel': 'Google ਲੌਗਿਨ ਰੱਦ ਕਰ ਦਿੱਤਾ ਗਿਆ.',
      'google_timeout': 'Google ਲੌਗਿਨ ਦਾ ਸਮਾਂ ਸਮਾਪਤ ਹੋ ਗਿਆ.',
      'google_setup_error': 'Google ਲੌਗਿਨ ਸੈੱਟਅੱਪ ਅਧੂਰਾ ਹੈ.',
      'future_waiting': 'ਤੁਹਾਡਾ ਭਵਿੱਖ ਅੰਦਰ ਉਡੀਕ ਕਰ ਰਿਹਾ ਹੈ...',
      'welcome_sine': 'Sine AI ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
      'enter_email_reset': 'ਪਾਸਵਰਡ ਰੀਸੈਟ ਕਰਨ ਲਈ ਈਮੇਲ ਪਾਓ',
      'reset_link_sent': 'ਪਾਸਵਰਡ ਰੀਸੈਟ ਲਿੰਕ ਭੇਜ ਦਿੱਤਾ ਗਿਆ ਹੈ',
      'error_reset_link': 'ਲਿੰਕ ਭੇਜਣ ਵਿੱਚ ਗਲਤੀ ਆਈ ਹੈ।',
      'account_not_found': 'ਖਾਤਾ ਨਹੀਂ ਮਿਲਿਆ।',
      'incorrect_password': 'ਗਲਤ ਪਾਸਵਰਡ।',
      'error_generic': 'ਗਲਤੀ ਆਈ ਹੈ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'friendly': 'ਮਿਲਣਸਾਰ 😊',
      'savage': 'ਸੈਵੇਜ 😈',
      'motivator': 'ਪ੍ਰੇਰਕ 💪',
      'chill': 'ਚਿੱਲ 😎',
      'privacy_title': 'ਪ੍ਰਾਈਵੇਸੀ',
      'privacy_desc': 'ਤੁਹਾਡਾ ਖਾਤਾ Firebase Auth ਨਾਲ ਸੁਰੱਖਿਅਤ ਹੈ।',
      'done': 'ਹੋ ਗਿਆ',
      'default_user_name': 'SINE AI ਵਰਤੋਂਕਾਰ',
      'default_bio': 'ਕੁਝ ਖਾਸ ਬਣਾ ਰਹੇ ਹਾਂ ✨',
      'chats': 'ਚੈਟ',
      'goals': 'ਟੀਚੇ',
      'streak': 'ਲਗਾਤਾਰ',
      'language_label': 'ਭਾਸ਼ਾ',
      'appearance': 'ਦਿੱਖ',
      'themes_free': 'ਥੀਮ ਮੁਫਤ ਹਨ',
      'notifications': 'ਨੋਟੀਫਿਕੇਸ਼ਨ',
      'notifications_desc': 'SINE ਅਲਰਟ ਸੈਟਿੰਗਾਂ',
      'aura_customization': 'ਆਪਣੀ AI ਨੂੰ ਬਦਲੋ',
      'privacy_label': 'ਪ੍ਰਾਈਵੇਸੀ',
      'privacy_sub': 'ਡਾਟਾ ਅਤੇ ਸੁਰੱਖਿਆ',
      'subscription_label': 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ',
      'subscription_sub': 'ਪਲਾਨ ਅਤੇ ਬਿਲਿੰਗ',
      'logout_label': 'ਲੌਗਆਉਟ',
      'logout_sub': 'ਖਾਤੇ ਤੋਂ ਬਾਹਰ ਜਾਓ',
      'choose_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'pro_title': 'SINE AI ਪ੍ਰੋ',
      'pro_message': 'ਅਸੀਮਤ ਚੈਟ ਅਤੇ ਹੋਰ ਫੀਚਰ ਖੋਲ੍ਹੋ।',
      'chat_initial': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ SINE AI ਹਾਂ। ਅੱਜ ਮੈਂ ਤੁਹਾਡੀ ਕੀ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?',
      'chat_hint': 'SINE AI ਨੂੰ ਮੈਸੇਜ ਭੇਜੋ...',
    },
    'sanskrit': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'सक्रियः',
      'chat': 'संवादः',
      'alerts': 'सूचनाः',
      'profile': 'विवरणम्',
      'welcome_back': 'स्वागतम्! 👋',
      'aura_waiting': 'AURA प्रतीक्षते...',
      'email': 'ई-पत्र संकेत:',
      'password': 'कूटशब्द:',
      'login': 'प्रविशतु ✦',
      'or': 'वा',
      'google_login': 'Google माध्यमेन प्रविशतु',
      'create_account': 'खातं रचयतु! ✨',
      'username_taken': 'एतत् नाम अन्येन गृहीतम्.',
      'new_here': 'नूतनः अस्ति वा? ',
      'forgot_password': 'कूटशब्दं विस्मृतवान्?',
      'smart_alarms': 'दक्ष-घटिका ⏰',
      'aura_talk': 'AURA सह भाषतु...',
      'upgrade': 'उन्नयनम्',
      'voice_unlock': 'वाणी AI उद्घाटयतु — ₹399/मासः',
      'settings': 'समायोजनम्',
      'free_plan': 'निशुल्क योजना',
      'upgrade_unlock': 'सर्वं उद्घाटयतु',
      'beyond_intelligence': 'बुद्धेः परम्',
      'initializing': 'AURA आरभते...',
      'verify_email': 'ई-पत्रं प्रमाणीकरोतु',
      'email_sent_to': 'प्रमाणीकरण सूत्रं प्रेषितम्:',
      'click_to_verify': 'प्रमाणीकृत्य "Maine Verify Kar Liya" नुदतु.',
      'i_have_verified': 'मया प्रमाणीकृतम् ✓',
      'resend_email': 'पुनः प्रेषयतु',
      'timer_expired': 'समयः समाप्तः. पुनः रचयतु.',
      'account_created_success': 'खातं रचितम्',
      'please_login_continue': 'प्रवेशं करोतु',
      'full_name': 'पूर्णं नाम',
      'name_email_pass_req': 'नाम, ई-पत्रं, कूटशब्दः च आवश्यकम्.',
      'username_req': 'विशिष्टं नाम लिखतु.',
      'bio_hint': 'स्वपरिचयः लिखतु',
      'choose_avatar': 'चित्रं चिनोतु',
      'aura_personality': 'AURA स्वभावः',
      'friendly_desc': 'दयालुः सहायकः च',
      'savage_desc': 'तीक्ष्णबुद्धिः',
      'motivator_desc': 'प्रेरकः',
      'chill_desc': 'शान्तः',
      'next': 'अग्रे →',
      'enter_email': 'ई-पत्रं लिखतु',
      'invalid_email': 'अशुद्धं ई-पत्रम्',
      'enter_password': 'कूटशब्दं लिखतु',
      'password_too_short': 'कूटशब्दः ६ वर्णात्मकः भवेत्',
      'email_not_verified': 'प्रमाणीकरणं न जातम्.',
      'login_failed': 'प्रवेशः विफलः.',
      'google_cancel': 'निरस्तम्.',
      'google_timeout': 'समयः समाप्तः.',
      'google_setup_error': 'दोषः जातः.',
      'future_waiting': 'भवतः भविष्यं प्रतीक्षते...',
      'welcome_sine': 'Sine AI मध्ये स्वागतम्',
      'enter_email_reset': 'पुनः स्थापनार्थं ई-पत्रं लिखतु',
      'reset_link_sent': 'सूत्रं प्रेषितम्',
      'error_reset_link': 'दोषः जातः।',
      'account_not_found': 'खाता न प्राप्तम्।',
      'incorrect_password': 'अशुद्धः कूटशब्दः।',
      'error_generic': 'दोषः जातः। पुनः प्रयतस्व।',
      'friendly': 'मित्रवत 😊',
      'savage': 'तीक्ष्ण 😈',
      'motivator': 'प्रेरक 💪',
      'chill': 'शान्त 😎',
      'privacy_title': 'गोपनीयता',
      'privacy_desc': 'भवतः खातं सुरक्षितम् अस्ति।',
      'done': 'कृतम्',
      'default_user_name': 'SINE AI प्रयोक्ता',
      'default_bio': 'किञ्चित् अद्भुतं रचयामि ✨',
      'chats': 'संवादाः',
      'goals': 'लक्ष्याणि',
      'streak': 'निरन्तरता',
      'language_label': 'भाषा',
      'appearance': 'स्वरूपम्',
      'themes_free': 'चित्राणि निःशुल्कानि सन्ति',
      'notifications': 'सूचनाः',
      'notifications_desc': 'SINE सूचना समायोजनम्',
      'aura_customization': 'स्वकीय AI रचयतु',
      'privacy_label': 'गोपनीयता',
      'privacy_sub': 'दत्तांशः सुरक्षा च',
      'subscription_label': 'सदस्यता',
      'subscription_sub': 'योजनाः शुल्कं च',
      'logout_label': 'निर्गमनम्',
      'logout_sub': 'खातात् निर्गच्छतु',
      'choose_language': 'भाषां चिनोतु',
      'pro_title': 'SINE AI प्रो',
      'pro_message': 'असीमित संवादः, वाणी AI च उद्घाटयतु।',
      'chat_initial': 'नमो नमः! अहं SINE AI अस्मि। अद्य कथं साहाय्यं करवाणि?',
      'chat_hint': 'SINE AI प्रति सन्देशं लिखतु...',
    },
    'tamil': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ஆன்லைன்',
      'chat': 'அரட்டை',
      'alerts': 'விழிப்பூட்டல்',
      'profile': 'சுயவிவரம்',
      'welcome_back': 'மீண்டும் வந்தீர்கள்! 👋',
      'aura_waiting': 'AURA உங்களுக்காக காத்திருந்தது...',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'login': 'உள்நுழை ✦',
      'or': 'அல்லது',
      'google_login': 'Google மூலம் தொடரவும்',
      'create_account': 'கணக்கை உருவாக்கு! ✨',
      'username_taken': 'இந்த username வேறு user எடுத்துவிட்டார்.',
      'new_here': 'புதியவரா? ',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'smart_alarms': 'ஸ்மார்ட் அலாரம் ⏰',
      'aura_talk': 'AURA உடன் பேசு...',
      'upgrade': 'மேம்படுத்து',
      'voice_unlock': 'Voice AI திற — ₹399/மாதம்',
      'settings': 'அமைப்புகள்',
      'free_plan': 'இலவச திட்டம்',
      'upgrade_unlock': 'அனைத்தையும் திறக்கவும்',
      'beyond_intelligence': 'அறிவுக்கு அப்பால்',
      'initializing': 'AURA தொடங்குகிறது...',
      'verify_email': 'மின்னஞ்சலைச் சரிபார்க்கவும்',
      'email_sent_to': 'சரிபார்ப்பு இணைப்பு அனுப்பப்பட்டது:',
      'click_to_verify': 'சரிபார்த்துவிட்டு "Maine Verify Kar Liya" என்பதைக் கிளிக் செய்யவும்.',
      'i_have_verified': 'நான் சரிபார்த்துவிட்டேன் ✓',
      'resend_email': 'மீண்டும் அனுப்பு',
      'timer_expired': 'காலாவதியானது. மீண்டும் முயற்சிக்கவும்.',
      'account_created_success': 'கணக்கு உருவாக்கப்பட்டது',
      'please_login_continue': 'தொடர உள்நுழையவும்',
      'full_name': 'முழு பெயர்',
      'name_email_pass_req': 'பெயர், மின்னஞ்சல் மற்றும் கடவுச்சொல் தேவை.',
      'username_req': 'தனித்துவமான பெயரை உள்ளிடவும்.',
      'bio_hint': 'உங்களைப் பற்றிச் சொல்லுங்கள்',
      'choose_avatar': 'அவதாரைத் தேர்வுசெய்க',
      'aura_personality': 'AURA ஆளுமை',
      'friendly_desc': 'அன்பான மற்றும் உதவும்',
      'savage_desc': 'கிண்டல் செய்யும்',
      'motivator_desc': 'ஊக்கமளிக்கும்',
      'chill_desc': 'அமைதியான முறை',
      'next': 'அடுத்து →',
      'enter_email': 'மின்னஞ்சலை உள்ளிடவும்',
      'invalid_email': 'தவறான மின்னஞ்சல்',
      'enter_password': 'கடவுச்சொல்லை உள்ளிடவும்',
      'password_too_short': 'குறைந்தது 6 எழுத்துக்கள் இருக்க வேண்டும்',
      'email_not_verified': 'சரிபார்க்கப்படவில்லை. இணைப்பு அனுப்பப்பட்டது.',
      'login_failed': 'தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
      'google_cancel': 'ரத்து செய்யப்பட்டது.',
      'google_timeout': 'நேரம் முடிந்தது.',
      'google_setup_error': 'அமைப்பு பிழை.',
      'future_waiting': 'உங்கள் எதிர்காலம் காத்திருக்கிறது...',
      'welcome_sine': 'Sine AI-க்கு வரவேற்கிறோம்',
      'enter_email_reset': 'மீட்டமைக்க மின்னஞ்சலை உள்ளிடவும்',
      'reset_link_sent': 'இணைப்பு அனுப்பப்பட்டது',
      'error_reset_link': 'இணைப்பை அனுப்புவதில் பிழை.',
      'account_not_found': 'கணக்கு இல்லை.',
      'incorrect_password': 'தவறான கடவுச்சொல்.',
      'error_generic': 'பிழை. மீண்டும் முயற்சிக்கவும்.',
      'friendly': 'நட்பான 😊',
      'savage': 'கோபமான 😈',
      'motivator': 'ஊக்கப்படுத்தும் 💪',
      'chill': 'அமைதியான 😎',
      'privacy_title': 'தனியுரிமை',
      'privacy_desc': 'உங்கள் கணக்கு பாதுகாப்பானது.',
      'done': 'முடிந்தது',
      'default_user_name': 'SINE AI பயனர்',
      'default_bio': 'அற்புதமான ஒன்றை உருவாக்குகிறோம் ✨',
      'chats': 'அரட்டைகள்',
      'goals': 'இலக்குகள்',
      'streak': 'தொடர்ச்சி',
      'language_label': 'மொழி',
      'appearance': 'தோற்றம்',
      'themes_free': 'தீம்கள் இலவசம்',
      'notifications': 'அறிவிப்புகள்',
      'notifications_desc': 'அலார அமைப்புகள்',
      'aura_customization': 'AI-ஐ மாற்றியமைக்கவும்',
      'privacy_label': 'தனியுரிமை',
      'privacy_sub': 'தரவு மற்றும் பாதுகாப்பு',
      'subscription_label': 'சந்தா',
      'subscription_sub': 'திட்டங்கள் மற்றும் கட்டணம்',
      'logout_label': 'வெளியேறு',
      'logout_sub': 'கணக்கிலிருந்து வெளியேறவும்',
      'choose_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'pro_title': 'SINE AI Pro',
      'pro_message': 'அளவற்ற அரட்டை மற்றும் பல வசதிகளைப் பெறுங்கள்.',
      'chat_initial': 'வணக்கம்! நான் SINE AI. உங்களுக்கு இன்று நான் எப்படி உதவ முடியும்?',
      'chat_hint': 'SINE AI-க்கு செய்தி அனுப்பவும்...',
    },
    'telugu': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ఆన్‌లైన్',
      'chat': 'చాట్',
      'alerts': 'అలెర్ట్స్',
      'profile': 'ప్రొఫైల్',
      'welcome_back': 'తిరిగి వచ్చినందుకు స్వాగతం! 👋',
      'aura_waiting': 'AURA మీ కోసం వేచి ఉంది...',
      'email': 'ఈమెయిల్ అడ్రస్',
      'password': 'పాస్‌వర్డ్',
      'login': 'లాగిన్ ✦',
      'or': 'లేదా',
      'google_login': 'Google తో కొనసాగండి',
      'create_account': 'ఖాతా సృష్టించండి! ✨',
      'username_taken': 'ఈ యూజర్‌నేమ్ ఇప్పటికే తీసుకోబడింది.',
      'new_here': 'కొత్తవారా? ',
      'forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'smart_alarms': 'స్మార్ట్ అలారాలు ⏰',
      'aura_talk': 'AURA తో మాట్లాడండి...',
      'upgrade': 'అప్‌గ్రేడ్',
      'voice_unlock': 'Voice AI అన్‌లాక్ — ₹399/నెల',
      'settings': 'సెట్టింగ్స్',
      'free_plan': 'ఉచిత ప్లాన్',
      'upgrade_unlock': 'అన్నీ అన్‌లాక్ చేయండి',
      'beyond_intelligence': 'తెలివితేటలకు మించి',
      'initializing': 'AURA ప్రారంభమవుతోంది...',
      'verify_email': 'ఈమెయిల్ వెరిఫై చేయండి',
      'email_sent_to': 'వెరిఫికేషన్ లింక్ పంపబడింది:',
      'click_to_verify': 'వెరిఫై చేసి "Maine Verify Kar Liya" పై క్లిక్ చేయండి.',
      'i_have_verified': 'నేను వెరిఫై చేశాను ✓',
      'resend_email': 'ఈమెయిల్ మళ్ళీ పంపు',
      'timer_expired': 'సమయం ముగిసింది. మళ్ళీ ప్రయత్నించండి.',
      'account_created_success': 'ఖాతా విజయవంతంగా సృష్టించబడింది',
      'please_login_continue': 'కొనసాగడానికి లాగిన్ అవ్వండి',
      'full_name': 'పూర్తి పేరు',
      'name_email_pass_req': 'పేరు, ఈమెయిల్ మరియు పాస్‌వర్డ్ అవసరం.',
      'username_req': 'ప్రత్యేకమైన యూజర్‌నేమ్ నమోదు చేయండి.',
      'bio_hint': 'మీ గురించి చెప్పండి',
      'choose_avatar': 'అవతార్ ఎంచుకోండి',
      'aura_personality': 'AURA వ్యక్తిత్వం',
      'friendly_desc': 'స్నేహపూర్వక మరియు సహాయక',
      'savage_desc': 'సరదాగా ఏడిపిస్తుంది',
      'motivator_desc': 'ఎల్లప్పుడూ ప్రోత్సహిస్తుంది',
      'chill_desc': 'ప్రశాంతంగా ఉంటుంది',
      'next': 'తదుపరి →',
      'enter_email': 'ఈమెయిల్ నమోదు చేయండి',
      'invalid_email': 'తప్పుడు ఈమెయిల్',
      'enter_password': 'పాస్‌వర్డ్ నమోదు చేయండి',
      'password_too_short': 'కనీసం 6 అక్షరాలు ఉండాలి',
      'email_not_verified': 'వెరిఫై కాలేదు. లింక్ పంపబడింది.',
      'login_failed': 'లాగిన్ విఫలమైంది.',
      'google_cancel': 'రద్దు చేయబడింది.',
      'google_timeout': 'సమయం ముగిసింది.',
      'google_setup_error': 'ఏర్పాటులో లోపం.',
      'future_waiting': 'మీ భవిష్యత్తు వేచి ఉంది...',
      'welcome_sine': 'Sine AI కి స్వాగతం',
      'enter_email_reset': 'రీసెట్ చేయడానికి ఈమెయిల్ ఇవ్వండి',
      'reset_link_sent': 'లింక్ పంపబడింది',
      'error_reset_link': 'లింక్ పంపడంలో లోపం.',
      'account_not_found': 'ఖాతా కనుగొనబడలేదు.',
      'incorrect_password': 'తప్పుడు పాస్‌వర్డ్.',
      'error_generic': 'లోపం. మళ్ళీ ప్రయత్నించండి.',
      'friendly': 'స్నేహపూర్వక 😊',
      'savage': 'సావేజ్ 😈',
      'motivator': 'ప్రేరణ 💪',
      'chill': 'ప్రశాంతం 😎',
      'privacy_title': 'గోప్యత',
      'privacy_desc': 'మీ ఖాతా సురక్షితంగా ఉంది.',
      'done': 'పూర్తయింది',
      'default_user_name': 'SINE AI వినియోగదారు',
      'default_bio': 'అద్భుతమైనదాన్ని నిర్మిస్తున్నాము ✨',
      'chats': 'చాట్లు',
      'goals': 'లక్ష్యాలు',
      'streak': 'స్ట్రీక్',
      'language_label': 'భాష',
      'appearance': 'రూపం',
      'themes_free': 'థీమ్స్ ఉచితం',
      'notifications': 'నోటిఫికేషన్లు',
      'notifications_desc': 'SINE అలర్ట్ సెట్టింగ్స్',
      'aura_customization': 'మీ AI ని మార్చుకోండి',
      'privacy_label': 'గోప్యత',
      'privacy_sub': 'డేటా & భద్రత',
      'subscription_label': 'సబ్‌స్క్రిప్షన్',
      'subscription_sub': 'ప్లాన్లు & బిల్లింగ్',
      'logout_label': 'లాగ్అవుట్',
      'logout_sub': 'ఖాతా నుండి నిష్క్రమించండి',
      'choose_language': 'భాషను ఎంచుకోండి',
      'pro_title': 'SINE AI ప్రో',
      'pro_message': 'అపరిమిత చాట్ మరియు మరిన్ని అన్‌లాక్ చేయండి.',
      'chat_initial': 'నమస్కారం! నేను SINE AI. ఈ రోజు మీకు ఎలా సహాయపడగలను?',
      'chat_hint': 'SINE AI కి సందేశం పంపండి...',
    },
    'kannada': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ಆನ್‌ಲೈನ್',
      'chat': 'ಚಾಟ್',
      'alerts': 'ಅಲರ್ಟ್ಸ್',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'welcome_back': 'ಮರಳಿ ಬಂದಿದ್ದಕ್ಕೆ ಸ್ವಾಗತ! 👋',
      'aura_waiting': 'AURA ನಿಮಗಾಗಿ ಕಾಯುತ್ತಿದೆ...',
      'email': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'login': 'ಲಾಗಿನ್ ✦',
      'or': 'ಅಥವಾ',
      'google_login': 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
      'create_account': 'ಖಾತೆ ತೆರೆಯಿರಿ! ✨',
      'username_taken': 'ಈ ಬಳಕೆದಾರಹೆಸರು ಈಗಾಗಲೇ ಬಳಕೆಯಲ್ಲಿದೆ.',
      'new_here': 'ಹೊಸಬರೇ? ',
      'forgot_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದೆಯೇ?',
      'smart_alarms': 'ಸ್ಮಾರ್ಟ್ ಅಲಾರಂಗಳು ⏰',
      'aura_talk': 'AURA ಜೊತೆ ಮಾತನಾಡಿ...',
      'upgrade': 'ಅಪ್‌ಗ್ರೇಡ್',
      'voice_unlock': 'Voice AI ಅನ್‌ಲಾಕ್ — ₹399/ತಿಂಗಳು',
      'settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'free_plan': 'ಉಚಿತ ಪ್ಲಾನ್',
      'upgrade_unlock': 'ಎಲ್ಲವನ್ನೂ ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
      'beyond_intelligence': 'ಬುದ್ಧಿವಂತಿಕೆಗೂ ಮೀರಿ',
      'initializing': 'AURA ಪ್ರಾರಂಭವಾಗುತ್ತಿದೆ...',
      'verify_email': 'ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ',
      'email_sent_to': 'ಪರಿಶೀಲನಾ ಲಿಂಕ್ ಕಳುಹಿಸಲಾಗಿದೆ:',
      'click_to_verify': 'ಪರಿಶೀಲಿಸಿ "Maine Verify Kar Liya" ಕ್ಲಿಕ್ ಮಾಡಿ.',
      'i_have_verified': 'ನಾನು ಪರಿಶೀಲಿಸಿದ್ದೇನೆ ✓',
      'resend_email': 'ಮತ್ತೆ ಕಳುಹಿಸಿ',
      'timer_expired': 'ಸಮಯ ಮೀರಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      'account_created_success': 'ಖಾತೆ ಸೃಷ್ಟಿಯಾಗಿದೆ',
      'please_login_continue': 'ಮುಂದುವರಿಯಲು ಲಾಗಿನ್ ಆಗಿ',
      'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
      'name_email_pass_req': 'ಹೆಸರು, ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯವಿದೆ.',
      'username_req': 'ವಿಶಿಷ್ಟ ಹೆಸರು ನಮೂದಿಸಿ.',
      'bio_hint': 'ನಿಮ್ಮ ಬಗ್ಗೆ ತಿಳಿಸಿ',
      'choose_avatar': 'ಅವತಾರ ಆರಿಸಿ',
      'aura_personality': 'AURA ವ್ಯಕ್ತಿತ್ವ',
      'friendly_desc': 'ಸ್ನೇಹಪರ ಮತ್ತು ಸಹಕಾರಿ',
      'savage_desc': 'ತಮಾಷೆ ಮಾಡುತ್ತದೆ',
      'motivator_desc': 'ಉತ್ತೇಜಿಸುತ್ತದೆ',
      'chill_desc': 'ಶಾಂತವಾಗಿ ಇರುತ್ತದೆ',
      'next': 'ಮುಂದೆ →',
      'enter_email': 'ಇಮೇಲ್ ನಮೂದಿಸಿ',
      'invalid_email': 'ತಪ್ಪು ಇಮೇಲ್',
      'enter_password': 'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
      'password_too_short': 'ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಲಿ',
      'email_not_verified': 'ಪರಿಶೀಲನೆಯಾಗಿಲ್ಲ. ಲಿಂಕ್ ಕಳುಹಿಸಲಾಗಿದೆ.',
      'login_failed': 'ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ.',
      'google_cancel': 'ರದ್ದಾಗಿದೆ.',
      'google_timeout': 'ಸಮಯ ಮುಗಿದಿದೆ.',
      'google_setup_error': 'ಸೆಟಪ್ ದೋಷ.',
      'future_waiting': 'ನಿಮ್ಮ ಭವಿಷ್ಯ ಕಾಯುತ್ತಿದೆ...',
      'welcome_sine': 'Sine AI ಗೆ ಸ್ವಾಗತ',
      'enter_email_reset': 'ಮರುಹೊಂದಿಸಲು ಇಮೇಲ್ ನೀಡಿ',
      'reset_link_sent': 'ಲಿಂಕ್ ಕಳುಹಿಸಲಾಗಿದೆ',
      'error_reset_link': 'ಲಿಂಕ್ ಕಳುಹಿಸುವಲ್ಲಿ ದೋಷ.',
      'account_not_found': 'ಖಾತೆ ಕಂಡುಬಂದಿಲ್ಲ.',
      'incorrect_password': 'ತಪ್ಪು ಪಾಸ್‌ವರ್ಡ್.',
      'error_generic': 'ದೋಷ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      'friendly': 'ಸ್ನೇಹಪರ 😊',
      'savage': 'ಸಾವೇಜ್ 😈',
      'motivator': 'ಪ್ರೇರಕ 💪',
      'chill': 'ಶಾಂತ 😎',
      'privacy_title': 'ಗೌಪ್ಯತೆ',
      'privacy_desc': 'ನಿಮ್ಮ ಖಾತೆ ಸುರಕ್ಷಿತವಾಗಿದೆ.',
      'done': 'ಮುಗಿಯಿತು',
      'default_user_name': 'SINE AI ಬಳಕೆದಾರ',
      'default_bio': 'ಅದ್ಭುತವಾದುದನ್ನು ನಿರ್ಮಿಸುತ್ತಿದ್ದೇವೆ ✨',
      'chats': 'ಚಾಟ್‌ಗಳು',
      'goals': 'ಗುರಿಗಳು',
      'streak': 'ಸ್ಟ್ರೀಕ್',
      'language_label': 'ಭಾಷೆ',
      'appearance': 'ಗೋಚರತೆ',
      'themes_free': 'ಥೀಮ್‌ಗಳು ಉಚಿತ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'notifications_desc': 'SINE ಅಲರ್ಟ್ ಸೆಟ್ಟಿಂಗ್ಸ್',
      'aura_customization': 'ನಿಮ್ಮ AI ಅನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ',
      'privacy_label': 'ಗೌಪ್ಯತೆ',
      'privacy_sub': 'ಡೇಟಾ ಮತ್ತು ಭದ್ರತೆ',
      'subscription_label': 'ಚಂದಾದಾರಿಕೆ',
      'subscription_sub': 'ಪ್ಲಾನ್ ಮತ್ತು ಬಿಲ್ಲಿಂಗ್',
      'logout_label': 'ಲಾಗ್ಔಟ್',
      'logout_sub': 'ಖಾತೆಯಿಂದ ಹೊರಬನ್ನಿ',
      'choose_language': 'ಭಾಷೆ ಆರಿಸಿ',
      'pro_title': 'SINE AI ಪ್ರೊ',
      'pro_message': 'ಅನಿಯಮಿತ ಚಾಟ್ ಮತ್ತು ಹೆಚ್ಚಿನ ಫೀಚರ್ಸ್‌ಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ.',
      'chat_initial': 'ನಮಸ್ಕಾರ! ನಾನು SINE AI. ಇಂದು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?',
      'chat_hint': 'SINE AI ಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ...',
    },
    'malayalam': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ഓൺലൈൻ',
      'chat': 'ചാറ്റ്',
      'alerts': 'അലേർട്ടുകൾ',
      'profile': 'പ്രൊഫൈൽ',
      'welcome_back': 'സ്വാഗതം! 👋',
      'aura_waiting': 'AURA കാത്തിരിക്കുന്നു...',
      'email': 'ഇമെയിൽ',
      'password': 'പാസ്‌വേഡ്',
      'login': 'ലോഗിൻ ✦',
      'or': 'അല്ലെങ്കിൽ',
      'google_login': 'Google വഴി തുടരുക',
      'create_account': 'അക്കൗണ്ട് ഉണ്ടാക്കുക! ✨',
      'username_taken': 'ഈ പേര് നിലവിലുണ്ട്.',
      'new_here': 'പുതിയ ആളാണോ? ',
      'forgot_password': 'പാസ്‌വേഡ് മറന്നോ?',
      'smart_alarms': 'സ്മാർട്ട് അലാറം ⏰',
      'aura_talk': 'AURA-യോട് സംസാരിക്കൂ...',
      'upgrade': 'അപ്‌ഗ്രേഡ്',
      'voice_unlock': 'Voice AI അൺലോക്ക് — ₹399/മാസം',
      'settings': 'സെറ്റിംഗ്സ്',
      'free_plan': 'സൗജന്യ പ്ലാൻ',
      'upgrade_unlock': 'എല്ലാം അൺലോക്ക് ചെയ്യൂ',
      'beyond_intelligence': 'ബുദ്ധിക്കപ്പുറം',
      'initializing': 'AURA തുടങ്ങുന്നു...',
      'verify_email': 'ഇമെയിൽ വെരിഫൈ ചെയ്യൂ',
      'email_sent_to': 'ലിങ്ക് അയച്ചിട്ടുണ്ട്:',
      'click_to_verify': 'വെരിഫൈ ചെയ്തിട്ട് "Maine Verify Kar Liya" അമർത്തുക.',
      'i_have_verified': 'ഞാൻ വെരിഫൈ ചെയ്തു ✓',
      'resend_email': 'വീണ്ടും അയക്കുക',
      'timer_expired': 'സമയം കഴിഞ്ഞു. വീണ്ടും ശ്രമിക്കുക.',
      'account_created_success': 'അക്കൗണ്ട് തയ്യാറായി',
      'please_login_continue': 'തുടരാൻ ലോഗിൻ ചെയ്യുക',
      'full_name': 'പൂർണ്ണനാമം',
      'name_email_pass_req': 'പേര്, ഇമെയിൽ, പാസ്‌വേഡ് വേണം.',
      'username_req': 'വേറിട്ടൊരു പേര് നൽകുക.',
      'bio_hint': 'നിങ്ങളെക്കുറിച്ച് പറയൂ',
      'choose_avatar': 'അവതാർ തിരഞ്ഞെടുക്കൂ',
      'aura_personality': 'AURA വ്യക്തിത്വം',
      'friendly_desc': 'സ്നേഹമുള്ള പെരുമാറ്റം',
      'savage_desc': 'കളിയാക്കും',
      'motivator_desc': 'പ്രോത്സാഹിപ്പിക്കും',
      'chill_desc': 'ശാന്തമായിരിക്കും',
      'next': 'അടുത്തത് →',
      'enter_email': 'ഇമെയിൽ നൽകുക',
      'invalid_email': 'തെറ്റായ ഇമെയിൽ',
      'enter_password': 'പാസ്‌വേഡ് നൽകുക',
      'password_too_short': '6 അക്ഷരമെങ്കിലും വേണം',
      'email_not_verified': 'വെരിഫൈ ചെയ്തിട്ടില്ല.',
      'login_failed': 'ലോഗിൻ പരാജയപ്പെട്ടു.',
      'google_cancel': 'റദ്ദാക്കി.',
      'google_timeout': 'സമയം കഴിഞ്ഞു.',
      'google_setup_error': 'പിശക് സംഭവിച്ചു.',
      'future_waiting': 'നിങ്ങളുടെ ഭാവി കാത്തിരിക്കുന്നു...',
      'welcome_sine': 'Sine AI-യിലേക്ക് സ്വാഗതം',
      'enter_email_reset': 'പുനഃക്രമീകരിക്കാൻ ഇമെയിൽ നൽകുക',
      'reset_link_sent': 'ലിങ്ക് അയച്ചു',
      'error_reset_link': 'ലിങ്ക് അയയ്ക്കുന്നതിൽ പിശക്.',
      'account_not_found': 'അക്കൗണ്ട് കണ്ടെത്തിയില്ല.',
      'incorrect_password': 'തെറ്റായ പാസ്‌വേഡ്.',
      'error_generic': 'പിശക്. വീണ്ടും ശ്രമിക്കുക.',
      'friendly': 'സൗഹൃദപരമായ 😊',
      'savage': 'സാവേജ് 😈',
      'motivator': 'പ്രേരകം 💪',
      'chill': 'ചില്ല് 😎',
      'privacy_title': 'സ്വകാര്യത',
      'privacy_desc': 'നിങ്ങളുടെ അക്കൗണ്ട് സുരക്ഷിതമാണ്.',
      'done': 'ചെയ്തു',
      'default_user_name': 'SINE AI ഉപയോക്താവ്',
      'default_bio': 'പുതിയത് എന്തോ നിർമ്മിക്കുന്നു ✨',
      'chats': 'ചാറ്റുകൾ',
      'goals': 'ലക്ഷ്യങ്ങൾ',
      'streak': 'സ്ട്രീക്ക്',
      'language_label': 'ഭാഷ',
      'appearance': 'രൂപം',
      'themes_free': 'തീമുകൾ സൗജന്യമാണ്',
      'notifications': 'അറിയിപ്പുകൾ',
      'notifications_desc': 'SINE ക്രമീകരണങ്ങൾ',
      'aura_customization': 'AI ക്രമീകരിക്കുക',
      'privacy_label': 'സ്വകാര്യത',
      'privacy_sub': 'ഡാറ്റയും സുരക്ഷയും',
      'subscription_label': 'സബ്സ്ക്രിപ്ഷൻ',
      'subscription_sub': 'പ്ലാനുകളും ബില്ലിംഗും',
      'logout_label': 'ലോഗൗട്ട്',
      'logout_sub': 'അക്കൗണ്ടിൽ നിന്ന് പുറത്തിറങ്ങുക',
      'choose_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'pro_title': 'SINE AI പ്രോ',
      'pro_message': 'അൺലിമിറ്റഡ് ചാറ്റും മറ്റും ആസ്വദിക്കൂ.',
      'chat_initial': 'നമസ്കാരം! ഞാൻ SINE AI ആണ്. ഇന്ന് എനിക്ക് എങ്ങനെ സഹായിക്കാനാകും?',
      'chat_hint': 'SINE AI-ക്ക് സന്ദേശമയയ്‌ക്കൂ...',
    },
    'odia': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ଅନଲାଇନ୍',
      'chat': 'ଚାଟ୍',
      'alerts': 'ଆଲର୍ଟ',
      'profile': 'ପ୍ରୋଫାଇଲ୍',
      'welcome_back': 'ସ୍ୱାଗତ! 👋',
      'aura_waiting': 'AURA ଅପେକ୍ଷା କରିଛି...',
      'email': 'ଇମେଲ୍ ଠିକଣା',
      'password': 'ପାସୱାର୍ଡ',
      'login': 'ଲଗଇନ୍ ✦',
      'or': 'କିମ୍ବା',
      'google_login': 'Google ସହିତ ଜାରି ରଖନ୍ତୁ',
      'create_account': 'ଖାତା ଖୋଲନ୍ତୁ! ✨',
      'username_taken': 'ଏହି ନାମଟି ପୂର୍ବରୁ ଅଛି।',
      'new_here': 'ନୂଆ କି? ',
      'forgot_password': 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ?',
      'smart_alarms': 'ସ୍ମାର୍ଟ ଆଲାରାମ ⏰',
      'aura_talk': 'AURA ସହିତ କଥା ହୁଅନ୍ତୁ...',
      'upgrade': 'ଅପଗ୍ରେଡ୍',
      'voice_unlock': 'Voice AI ଅନଲକ୍ — ₹399/ମାସ',
      'settings': 'ସେଟିଙ୍ଗସ୍',
      'free_plan': 'ମାଗଣା ପ୍ଲାନ୍',
      'upgrade_unlock': 'ସବୁକିଛି ଅନଲକ୍ କରନ୍ତု',
      'beyond_intelligence': 'ବୁଦ୍ଧିମତା ବାହାରେ',
      'initializing': 'AURA ଆରମ୍ଭ ହେଉଛି...',
      'verify_email': 'ଇମେଲ୍ ଯାଞ୍ચ କରନ୍ତୁ',
      'email_sent_to': 'ଲିଙ୍କ୍ ପଠାଯାଇଛି:',
      'click_to_verify': 'ଯାଞ୍ଚ କରି "Maine Verify Kar Liya" କ୍ଲିକ୍ କରନ୍ତୁ।',
      'i_have_verified': 'ମୁଁ ଯାଞ୍ચ କରିଛି ✓',
      'resend_email': 'ପୁଣି ପଠାନ୍ତୁ',
      'timer_expired': 'ସମୟ ସରିଗଲା। ପୁଣି ଚେଷ୍ଟา କରନ୍ତୁ।',
      'account_created_success': 'ଖାତା ସଫଳତାପୂର୍ବକ ଖୋଲିଲା',
      'please_login_continue': 'ଆଗକୁ ବଢିବାକୁ ଲଗଇନ୍ କରନ୍ତୁ',
      'full_name': 'ପୁରା ନାମ',
      'name_email_pass_req': 'ନାମ, ଇମେଲ୍ ଏବଂ ପାସୱାର୍ଡ ଦରକାର।',
      'username_req': 'ଏକ ସ୍ୱତନ୍ତ୍ର ନାମ ଦିଅନ୍ତୁ।',
      'bio_hint': 'ନିଜ ବିଷୟରେ କିଛି କୁହନ୍ତୁ',
      'choose_avatar': 'ଅବତାର ବାଛନ୍ତୁ',
      'aura_personality': 'AURA ବ୍ୟକ୍ତିତ୍ୱ',
      'friendly_desc': 'ଦୟାଳୁ ଏବଂ ସାହାଯ୍ୟକାରୀ',
      'savage_desc': 'ମଜା କରିବ',
      'motivator_desc': 'ଉତ୍ସାହିତ କରିବ',
      'chill_desc': 'ଶାନ୍ତ ରହିବ',
      'next': 'ପରବର୍ତ୍ତୀ →',
      'enter_email': 'ଇମେଲ୍ ଦିଅନ୍ତୁ',
      'invalid_email': 'ଭୁଲ୍ ଇମେଲ୍',
      'enter_password': 'ପାସୱାର୍ଡ ଦିଅନ୍ତୁ',
      'password_too_short': 'ଅତିକମରେ ୬ ଅକ୍ଷର ଦରକାର',
      'email_not_verified': 'ଯାଞ୍ચ ହୋଇନାହିଁ।',
      'login_failed': 'ଲଗଇନ୍ ବିଫଳ ହେଲା।',
      'google_cancel': 'ବାତିଲ୍ ହେଲା।',
      'google_timeout': 'ସମୟ ସରିଗଲା।',
      'google_setup_error': 'ତ୍ରୁଟି ହେଲା।',
      'future_waiting': 'ଆପଣଙ୍କ ଭବିଷ୍ୟତ ଅପେକ୍ଷା କରିଛି...',
      'welcome_sine': 'Sine AI କୁ ସ୍ୱାଗତ',
      'enter_email_reset': 'ରିସେଟ୍ ପାଇଁ ଇମେଲ୍ ଦିଅନ୍ତୁ',
      'reset_link_sent': 'ଲିଙ୍କ୍ ପଠାଯାଇଛି',
      'error_reset_link': 'ଲିଙ୍କ୍ ପଠାଇବାରେ ତ୍ରୁଟି।',
      'account_not_found': 'ଖାତା ମିଳିଲା ନାହିଁ।',
      'incorrect_password': 'ଭୁଲ୍ ପାସୱାର୍ଡ।',
      'error_generic': 'ତ୍ରୁଟି। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।',
      'friendly': 'ବନ୍ଧୁତ୍ୱପୂର୍ଣ୍ଣ 😊',
      'savage': 'ସାଭେଜ୍ 😈',
      'motivator': 'ପ୍ରେରଣାଦାୟକ 💪',
      'chill': 'ଶାନ୍ତ 😎',
      'privacy_title': 'ଗୋପନୀୟତା',
      'privacy_desc': 'ଆପଣଙ୍କ ଖାତା ସୁରକ୍ଷିତ ଅଛି।',
      'done': 'ହୋଇଗଲା',
      'default_user_name': 'SINE AI ବ୍ୟବହାରକାରୀ',
      'default_bio': 'କିଛି ଭଲ ତିଆରି କରୁଛୁ ✨',
      'chats': 'ଚାଟ୍',
      'goals': 'ଲକ୍ଷ୍ୟ',
      'streak': 'ଲଗାତାର',
      'language_label': 'ଭାଷା',
      'appearance': 'ଦୃଶ୍ୟ',
      'themes_free': 'ଥିମ୍ ଗୁଡିକ ମାଗଣା',
      'notifications': 'ସୂଚନା',
      'notifications_desc': 'SINE ସେଟିଙ୍ଗସ୍',
      'aura_customization': 'AI କୁ ନିଜ ହିସାବରେ କରନ୍ତୁ',
      'privacy_label': 'ଗୋପନୀୟତା',
      'privacy_sub': 'ଡାଟା ଏବଂ ସୁରକ୍ଷା',
      'subscription_label': 'ସଦସ୍ୟତା',
      'subscription_sub': 'ପ୍ଲାନ୍ ଏବଂ ବିଲିଂ',
      'logout_label': 'ଲଗଆଉଟ୍',
      'logout_sub': 'ଖାତାରୁ ବାହାରକୁ ଯାଆନ୍ତୁ',
      'choose_language': 'ଭାଷା ବାଛନ୍ତୁ',
      'pro_title': 'SINE AI ପ୍ରୋ',
      'pro_message': 'ଅସୀମିତ ଚାଟ୍ ଏବଂ ଅନ୍ୟାନ୍ୟ ସୁବିଧା ପାଆନ୍ତୁ।',
      'chat_initial': 'ନମସ୍କାର! ମୁଁ SINE AI। ଆଜି ମୁଁ ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?',
      'chat_hint': 'SINE AI କୁ ମେସେଜ୍ ପଠାନ୍ତୁ...',
    },
    'bengali': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'অনলাইন',
      'chat': 'চ্যাট',
      'alerts': 'অ্যালার্ট',
      'profile': 'প্রোফাইল',
      'welcome_back': 'স্বাগতম! 👋',
      'aura_waiting': 'AURA অপেক্ষা করছে...',
      'email': 'ইমেল ঠিকানা',
      'password': 'পাসওয়ার্ড',
      'login': 'লগইন ✦',
      'or': 'অথবা',
      'google_login': 'Google দিয়ে চালিয়ে যান',
      'create_account': 'অ্যাকাউন্ট তৈরি করুন! ✨',
      'username_taken': 'এই ইউজারনেমটি আগে নেওয়া হয়েছে।',
      'new_here': 'নতুন? ',
      'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'smart_alarms': 'স্মার্ট অ্যালার্ম ⏰',
      'aura_talk': 'AURA-র সাথে কথা বলুন...',
      'upgrade': 'আপগ্রেড',
      'voice_unlock': 'Voice AI আনলক — ₹৩৯৯/মাস',
      'settings': 'সেটিংস',
      'free_plan': 'ফ্রি প্ল্যান',
      'upgrade_unlock': 'সব কিছু আনলক করুন',
      'beyond_intelligence': 'বুদ্ধিমত্তার ঊর্ধ্বে',
      'initializing': 'AURA শুরু হচ্ছে...',
      'verify_email': 'ইমেল যাচাই করুন',
      'email_sent_to': 'লিঙ্ক পাঠানো হয়েছে:',
      'click_to_verify': 'যাচাই করে "Maine Verify Kar Liya" ক্লিক করুন।',
      'i_have_verified': 'আমি যাচাই করেছি ✓',
      'resend_email': 'আবার পাঠান',
      'timer_expired': 'সময় শেষ। আবার চেষ্টা করুন।',
      'account_created_success': 'অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে',
      'please_login_continue': 'এগিয়ে যেতে লগইন করুন',
      'full_name': 'পুরো নাম',
      'name_email_pass_req': 'নাম, ইমেল এবং পাসওয়ার্ড প্রয়োজন।',
      'username_req': 'একটি ইউনিক নাম দিন।',
      'bio_hint': 'নিজের সম্পর্কে কিছু বলুন',
      'choose_avatar': 'অবতার বেছে নিন',
      'aura_personality': 'AURA ব্যক্তিত্ব',
      'friendly_desc': 'দয়ালু এবং সহায়ক',
      'savage_desc': 'মজা করবে',
      'motivator_desc': 'উৎসাহ দেবে',
      'chill_desc': 'শান্ত থাকবে',
      'next': 'পরবর্তী →',
      'enter_email': 'ইমেল দিন',
      'invalid_email': 'ভুল ইমেল',
      'enter_password': 'পাসওয়ার্ড দিন',
      'password_too_short': 'কমপক্ষে ৬ অক্ষর চাই',
      'email_not_verified': 'যাচাই করা হয়নি।',
      'login_failed': 'লগইন ব্যর্থ হয়েছে।',
      'google_cancel': 'বাতিল করা হয়েছে।',
      'google_timeout': 'সময় শেষ।',
      'google_setup_error': 'ত্রুটি হয়েছে।',
      'future_waiting': 'আপনার ভবিষ্যৎ অপেক্ষা করছে...',
      'welcome_sine': 'Sine AI-তে স্বাগতম',
      'enter_email_reset': 'রিসেট করতে ইমেল দিন',
      'reset_link_sent': 'লিঙ্ক পাঠানো হয়েছে',
      'error_reset_link': 'লিঙ্ক পাঠাতে ত্রুটি।',
      'account_not_found': 'অ্যাকাউন্ট পাওয়া যায়নি।',
      'incorrect_password': 'ভুল পাসওয়ার্ড।',
      'error_generic': 'ত্রুটি। আবার চেষ্টা করুন।',
      'friendly': 'বন্ধুত্বপূর্ণ 😊',
      'savage': 'স্যাভেজ 😈',
      'motivator': 'অনুপ্রেরণা 💪',
      'chill': 'চিল 😎',
      'privacy_title': 'গোপনীয়তা',
      'privacy_desc': 'আপনার অ্যাকাউন্ট নিরাপদ।',
      'done': 'সম্পন্ন',
      'default_user_name': 'SINE AI ব্যবহারকারী',
      'default_bio': 'অসাধারণ কিছু তৈরি করছি ✨',
      'chats': 'চ্যাট',
      'goals': 'লক্ষ্য',
      'streak': 'স্ট্রিক',
      'language_label': 'ভাষা',
      'appearance': 'চেহারা',
      'themes_free': 'থিমগুলি বিনামূল্যে',
      'notifications': 'বিজ্ঞপ্তি',
      'notifications_desc': 'SINE সেটিংস',
      'aura_customization': 'আপনার AI কাস্টমাইজ করুন',
      'privacy_label': 'গোপনীয়তা',
      'privacy_sub': 'ডেটা এবং নিরাপত্তা',
      'subscription_label': 'সাবস্ক্রিপশন',
      'subscription_sub': 'প্ল্যান এবং বিলিং',
      'logout_label': 'লগআউট',
      'logout_sub': 'অ্যাকাউন্ট থেকে বেরিয়ে যান',
      'choose_language': 'ভাষা চয়ন করুন',
      'pro_title': 'SINE AI প্রো',
      'pro_message': 'আনলিমিটেড চ্যাট এবং প্রিমিয়াম সুবিধাগুলি আনলক করুন।',
      'chat_initial': 'নমস্কার! আমি SINE AI। আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?',
      'chat_hint': 'SINE AI-কে মেসেজ দিন...',
    },
    'marathi': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ऑनलाइन',
      'chat': 'चॅट',
      'alerts': 'अलर्ट्स',
      'profile': 'प्रोफाईल',
      'welcome_back': 'परत स्वागत आहे! 👋',
      'aura_waiting': 'AURA तुमची वाट पाहत आहे...',
      'email': 'ईमेल पत्ता',
      'password': 'पासवर्ड',
      'login': 'लॉगिन ✦',
      'or': 'किंवा',
      'google_login': 'Google सह सुरू ठेवा',
      'create_account': 'अकाऊंट बनवा! ✨',
      'username_taken': 'हे युजरनेम आधीच घेतले गेले आहे.',
      'new_here': 'नवीन आहात? ',
      'forgot_password': 'पासवर्ड विसरलात?',
      'smart_alarms': 'स्मार्ट अलार्म ⏰',
      'aura_talk': 'AURA शी बोला...',
      'upgrade': 'अपग्रेड',
      'voice_unlock': 'Voice AI अनलॉक — ₹३९९/महिना',
      'settings': 'सेटिंग्ज',
      'free_plan': 'फ्री प्लॅन',
      'upgrade_unlock': 'सर्व काही अनलॉक करा',
      'beyond_intelligence': 'बुद्धिमत्तेच्या पलीकडे',
      'initializing': 'AURA सुरू होत आहे...',
      'verify_email': 'ईमेल व्हेरिफाय करा',
      'email_sent_to': 'व्हेरिफिकेशन लिंक येथे पाठवली आहे:',
      'click_to_verify': 'व्हेरिफाय करून "Maine Verify Kar Liya" वर क्लिक करा.',
      'i_have_verified': 'मी व्हेरिफाय केले आहे ✓',
      'resend_email': 'ईमेल पुन्हा पाठवा',
      'timer_expired': 'वेळ संपली. कृपया पुन्हा प्रयत्न करा.',
      'account_created_success': 'अकाऊंट यशस्वीरित्या तयार झाले',
      'please_login_continue': 'पुढे जाण्यासाठी लॉगिन करा',
      'full_name': 'पूर्ण नाव',
      'name_email_pass_req': 'नाव, ईमेल आणि पासवर्ड आवश्यक आहेत.',
      'username_req': 'कृपया एक युनिक युजरनेम टाका.',
      'bio_hint': 'बायो - स्वतःबद्दल काही सांगा',
      'choose_avatar': 'अवतार निवडा',
      'aura_personality': 'AURA स्वभाव',
      'friendly_desc': 'दयाळू आणि मदत करणारा',
      'savage_desc': 'रोस्ट करेल',
      'motivator_desc': 'नेहमी प्रोत्साहित करेल',
      'chill_desc': 'नेहमी रिलॅक्स मोड',
      'next': 'पुढे →',
      'enter_email': 'कृपया ईमेल टाका',
      'invalid_email': 'ईमेल फॉरमॅट चुकीचा आहे',
      'enter_password': 'कृपया पासवर्ड टाका',
      'password_too_short': 'पासवर्ड किमान ६ अक्षरांचा हवा',
      'email_not_verified': 'ईमेल व्हेरिफाय नाही. लिंक पाठवली आहे.',
      'login_failed': 'लॉगिन अयशस्वी. पुन्हा प्रयत्न करा.',
      'google_cancel': 'Google लॉगिन रद्द झाले.',
      'google_timeout': 'Google लॉगिन वेळ संपली.',
      'google_setup_error': 'Google लॉगिन सेटअप त्रुटी.',
      'future_waiting': 'तुमचे भविष्य आत वाट पाहत आहे...',
      'welcome_sine': 'Sine AI मध्ये स्वागत आहे',
      'enter_email_reset': 'रिसेट करण्यासाठी ईमेल टाका',
      'reset_link_sent': 'रिसेट लिंक पाठवली आहे',
      'error_reset_link': 'लिंक पाठवण्यात त्रुटी आली।',
      'account_not_found': 'अकाऊंट सापडले नाही।',
      'incorrect_password': 'चुकीचा पासवर्ड।',
      'error_generic': 'त्रुटी आली। पुन्हा प्रयत्न करा।',
      'friendly': 'प्रेमळ 😊',
      'savage': 'सैवेज 😈',
      'motivator': 'प्रेरक 💪',
      'chill': 'चिल 😎',
      'privacy_title': 'गोपनीयता',
      'privacy_desc': 'तुमचे अकाऊंट सुरक्षित आहे।',
      'done': 'झाले',
      'default_user_name': 'SINE AI वापरकर्ता',
      'default_bio': 'काहीतरी अप्रतिम बनवत आहोत ✨',
      'chats': 'चॅट्स',
      'goals': 'ध्येय',
      'streak': 'स्ट्रीक',
      'language_label': 'भाषा',
      'appearance': 'स्वरूप',
      'themes_free': 'थीम्स मोफत आहेत',
      'notifications': 'सूचना',
      'notifications_desc': 'SINE अलर्ट सेटिंग्ज',
      'aura_customization': 'तुमची AI कस्टमाइझ करा',
      'privacy_label': 'गोपनीयता',
      'privacy_sub': 'डेटा आणि सुरक्षा',
      'subscription_label': 'सदस्यत्व',
      'subscription_sub': 'प्लॅन्स आणि बिलिंग',
      'logout_label': 'लॉगआउट',
      'logout_sub': 'अकाऊंटमधून बाहेर पडा',
      'choose_language': 'भाषा निवडा',
      'pro_title': 'SINE AI प्रो',
      'pro_message': 'अमर्यादित चॅट आणि प्रीमियम वैशिष्ट्ये अनलॉक करा.',
      'chat_initial': 'नमस्कार! मी SINE AI आहे. आज मी तुम्हाला कशी मदत करू शकतो?',
      'chat_hint': 'SINE AI ला मेसेज पाठवा...',
    },
    'gujarati': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'ઓનલાઇન',
      'chat': 'ચેટ',
      'alerts': 'અલર્ટ',
      'profile': 'પ્રોફાઇલ',
      'welcome_back': 'પાછા સ્વાગત છે! 👋',
      'aura_waiting': 'AURA તમારી રાહ જોઈ રહ્યું છે...',
      'email': 'ઈમેલ એડ્રેસ',
      'password': 'પાસવર્ડ',
      'login': 'લોગિન ✦',
      'or': 'અથવા',
      'google_login': 'Google સાથે ચાલુ રાખો',
      'create_account': 'એકાઉન્ટ બનાવો! ✨',
      'username_taken': 'આ યુઝરનેમ કોઈએ લઈ લીધું છે.',
      'new_here': 'નવા છો? ',
      'forgot_password': 'પાસવર્ડ ભૂલી ગયા?',
      'smart_alarms': 'સ્માર્ટ એલાર્મ ⏰',
      'aura_talk': 'AURA સાથે વાત કરો...',
      'upgrade': 'અપગ્રેડ',
      'voice_unlock': 'Voice AI અનલોક — ₹399/મહિનો',
      'settings': 'સેટિંગ્સ',
      'free_plan': 'ફ્રી પ્લાન',
      'upgrade_unlock': 'બધું અનલોક કરો',
      'beyond_intelligence': 'બુદ્ધિથી પર',
      'initializing': 'AURA શરૂ થઈ રહ્યું છે...',
      'verify_email': 'ઈમેલ વેરીફાય કરો',
      'email_sent_to': 'વેરીફિકેશન લિંક મોકલી દીધી છે:',
      'click_to_verify': 'વેરીફાય કરી "Maine Verify Kar Liya" પર ક્લિક કરો.',
      'i_have_verified': 'મેં વેરીફાય કરી લીધું ✓',
      'resend_email': 'ઈમેલ ફરી મોકલો',
      'timer_expired': 'સમય પૂરો થયો. ફરી પ્રયત્ન કરો.',
      'account_created_success': 'એકાઉન્ટ સફળતાપૂર્વક બની ગયું',
      'please_login_continue': 'આગળ વધવા લોગિન કરો',
      'full_name': 'પૂરું નામ',
      'name_email_pass_req': 'નામ, ઈમેલ અને પાસવર્ડ જરૂરી છે.',
      'username_req': 'એક યુનિક યુઝરનેમ નાખો.',
      'bio_hint': 'તમારા વિશે કંઈક જણાવો',
      'choose_avatar': 'અવતાર પસંદ કરો',
      'aura_personality': 'AURA વ્યક્તિત્વ',
      'friendly_desc': 'દયાળુ અને મદદગાર',
      'savage_desc': 'રોસ્ટ કરશે',
      'motivator_desc': 'હંમેશા પ્રોત્સાહન આપશે',
      'chill_desc': 'શાંત સ્વભાવ',
      'next': 'આગળ →',
      'enter_email': 'ઈમેલ નાખો',
      'invalid_email': 'ખોટો ઈમેલ',
      'enter_password': 'પાસવર્ડ નાખો',
      'password_too_short': 'ઓછામાં ઓછા 6 અક્ષર જોઈએ',
      'email_not_verified': 'વેરીફાય નથી. લિંક મોકલી છે.',
      'login_failed': 'લોગિન નિષ્ફળ ગયું.',
      'google_cancel': 'રદ કરવામાં આવ્યું.',
      'google_timeout': 'સમય પૂરો થયો.',
      'google_setup_error': 'ભૂલ આવી છે.',
      'future_waiting': 'તમારું ભવિષ્ય અંદર રાહ જોવે છે...',
      'welcome_sine': 'Sine AI માં સ્વાગત છે',
      'enter_email_reset': 'રિસેટ કરવા ઈમેલ નાખો',
      'reset_link_sent': 'લિંક મોકલી દીધી છે',
      'error_reset_link': 'લિંક મોકલવામાં ભૂલ આવી।',
      'account_not_found': 'એકાઉન્ટ મળ્યું નથી।',
      'incorrect_password': 'ખોટો પાસવર્ડ।',
      'error_generic': 'ભૂલ આવી। ફરી પ્રયત્ન કરો।',
      'friendly': 'મિત્રતાપૂર્ણ 😊',
      'savage': 'સેવેજ 😈',
      'motivator': 'પ્રેરક 💪',
      'chill': 'શાંત 😎',
      'privacy_title': 'પ્રાઇવસી',
      'privacy_desc': 'તમારું એકાઉન્ટ સુરક્ષિત છે।',
      'done': 'થઈ ગયું',
      'default_user_name': 'SINE AI વપરાશકર્તા',
      'default_bio': 'કંઈક અદભૂત બનાવી રહ્યા છીએ ✨',
      'chats': 'ચેટ',
      'goals': 'લક્ષ્યો',
      'streak': 'સ્ટ્રીક',
      'language_label': 'ભાષા',
      'appearance': 'દેખાવ',
      'themes_free': 'થીમ્સ મફત છે',
      'notifications': 'નોટિફિકેશન',
      'notifications_desc': 'SINE અલર્ટ સેટિંગ્સ',
      'aura_customization': 'તમારી AI કસ્ટમાઇઝ કરો',
      'privacy_label': 'પ્રાઇવસી',
      'privacy_sub': 'ડેટા અને સુરક્ષા',
      'subscription_label': 'સબ્સ્ક્રિપ્શન',
      'subscription_sub': 'પ્લાન્સ અને બિલિંગ',
      'logout_label': 'લોગઆઉટ',
      'logout_sub': 'એકાઉન્ટમાંથી બહાર નીકળો',
      'choose_language': 'ભાષા પસંદ કરો',
      'pro_title': 'SINE AI પ્રો',
      'pro_message': 'અમર્યાદિત ચેટ અને પ્રીમિયમ સુવિધાઓ અનલોક કરો.',
      'chat_initial': 'નમસ્તે! હું SINE AI છું. આજે હું તમને કેવી રીતે મદદ કરી શકું?',
      'chat_hint': 'SINE AI ને મેસેજ મોકલો...',
    },
    'russian': {
      'app_name': 'SINE AI',
      'aura': 'AURA',
      'online': 'В сети',
      'chat': 'Чат',
      'alerts': 'Уведомления',
      'profile': 'Профиль',
      'welcome_back': 'С возвращением! 👋',
      'aura_waiting': 'AURA ждет вас...',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'login': 'Войти ✦',
      'or': 'или',
      'google_login': 'Продолжить через Google',
      'create_account': 'Создать аккаунт! ✨',
      'username_taken': 'Это имя пользователя уже занято.',
      'new_here': 'Впервые здесь? ',
      'forgot_password': 'Забыли пароль?',
      'smart_alarms': 'Умные будильники ⏰',
      'aura_talk': 'Поговорить с AURA...',
      'upgrade': 'Улучшить',
      'voice_unlock': 'Разблокировать Voice AI — ₹399/мес',
      'settings': 'Настройки',
      'free_plan': 'Бесплатный план',
      'upgrade_unlock': 'Разблокировать всё',
      'beyond_intelligence': 'Вне интеллекта',
      'initializing': 'Инициализация AURA...',
      'verify_email': 'Подтвердите почту',
      'email_sent_to': 'Ссылка для подтверждения отправлена на:',
      'click_to_verify': 'Подтвердите и нажмите "Я подтвердил".',
      'i_have_verified': 'Я подтвердил ✓',
      'resend_email': 'Отправить снова',
      'timer_expired': 'Срок истек. Зарегистрируйтесь снова.',
      'account_created_success': 'Аккаунт успешно создан',
      'please_login_continue': 'Пожалуйста, войдите, чтобы продолжить',
      'full_name': 'Полное имя',
      'name_email_pass_req': 'Имя, почта и пароль обязательны.',
      'username_req': 'Введите уникальное имя пользователя.',
      'bio_hint': 'О себе',
      'choose_avatar': 'ВЫБРАТЬ АВАТАР',
      'aura_personality': 'ХАРАКТЕР AURA',
      'friendly_desc': 'Теплый и заботливый',
      'savage_desc': 'Будет подшучивать',
      'motivator_desc': 'Всегда поддержит',
      'chill_desc': 'Всегда на расслабоне',
      'next': 'Далее →',
      'enter_email': 'Введите почту',
      'invalid_email': 'Неверный формат почты',
      'enter_password': 'Введите пароль',
      'password_too_short': 'Минимум 6 символов',
      'email_not_verified': 'Почта не подтверждена.',
      'login_failed': 'Ошибка входа.',
      'google_cancel': 'Отменено.',
      'google_timeout': 'Время ожидания истекло.',
      'google_setup_error': 'Ошибка настройки.',
      'future_waiting': 'Ваше будущее ждет внутри...',
      'welcome_sine': 'Добро пожаловать в Sine AI',
      'enter_email_reset': 'Введите почту для сброса',
      'reset_link_sent': 'Ссылка отправлена',
      'error_reset_link': 'Ошибка отправки ссылки.',
      'account_not_found': 'Аккаунт не найден.',
      'incorrect_password': 'Неверный пароль.',
      'error_generic': 'Ошибка. Попробуйте снова.',
      'friendly': 'Дружелюбный 😊',
      'savage': 'Дерзкий 😈',
      'motivator': 'Мотиватор 💪',
      'chill': 'Спокойный 😎',
      'privacy_title': 'Приватность',
      'privacy_desc': 'Ваш аккаунт защищен.',
      'done': 'Готово',
      'default_user_name': 'Пользователь SINE AI',
      'default_bio': 'Создаю что-то удивительное ✨',
      'chats': 'Чаты',
      'goals': 'Цели',
      'streak': 'Серия',
      'language_label': 'Язык',
      'appearance': 'Вид',
      'themes_free': 'Темы бесплатны',
      'notifications': 'Уведомления',
      'notifications_desc': 'Настройки SINE',
      'aura_customization': 'Настройте свой AI',
      'privacy_label': 'Приватность',
      'privacy_sub': 'Данные и защита',
      'subscription_label': 'Подписка',
      'subscription_sub': 'Планы и оплата',
      'logout_label': 'Выйти',
      'logout_sub': 'Выйти из аккаунта',
      'choose_language': 'Выберите язык',
      'pro_title': 'SINE AI Pro',
      'pro_message': 'Разблокируйте безлимитный чат и премиум-функции.',
      'chat_initial': 'Привет! Я SINE AI. Чем я могу помочь сегодня?',
      'chat_hint': 'Напишите SINE AI...',
    }
  };

  static String get(String key) {
    return _strings[currentLanguage]?[key] ?? _strings['english']?[key] ?? key;
  }

  static List<Map<String, String>> get allLanguages => [
        {'key': 'english', 'name': 'English', 'native': 'English', 'flag': '🇺🇸'},
        {'key': 'hindi', 'name': 'Hindi', 'native': 'हिंदी', 'flag': '🇮🇳'},
        {'key': 'haryanvi', 'name': 'Haryanvi', 'native': 'हरयाणवी', 'flag': '🇮🇳'},
        {'key': 'punjabi', 'name': 'Punjabi', 'native': 'ਪੰਜਾਬੀ', 'flag': '🇮🇳'},
        {'key': 'sanskrit', 'name': 'Sanskrit', 'native': 'संस्कृतम्', 'flag': '🇮🇳'},
        {'key': 'tamil', 'name': 'Tamil', 'native': 'தமிழ்', 'flag': '🇮🇳'},
        {'key': 'telugu', 'name': 'Telugu', 'native': 'తెలుగు', 'flag': '🇮🇳'},
        {'key': 'kannada', 'name': 'Kannada', 'native': 'ಕನ್ನಡ', 'flag': '🇮🇳'},
        {'key': 'malayalam', 'name': 'Malayalam', 'native': 'മലയാളം', 'flag': '🇮🇳'},
        {'key': 'odia', 'name': 'Odia', 'native': 'ଓଡ଼ିଆ', 'flag': '🇮🇳'},
        {'key': 'bengali', 'name': 'Bengali', 'native': 'বাংলা', 'flag': '🇮🇳'},
        {'key': 'marathi', 'name': 'Marathi', 'native': 'मराठी', 'flag': '🇮🇳'},
        {'key': 'gujarati', 'name': 'Gujarati', 'native': 'ગુજરાતી', 'flag': '🇮🇳'},
        {'key': 'russian', 'name': 'Russian', 'native': 'Русский', 'flag': '🇷🇺'},
      ];
}
